allowBuilds:
  '@reown/appkit': set this to true or false
  bufferutil: set this to true or false
  esbuild: true
  keccak: set this to true or false
  msw: true
  utf-8-validate: set this to true or false
