/**
 * Seeds the local database and object storage with the demo creator, the four demo videos
 * (segments from frontend/public/demo, generated by `pnpm demo:assets` there) and a few settled
 * historical sessions so lists are not empty. Idempotent.
 */
import { createReadStream } from "node:fs";
import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { eq } from "drizzle-orm";
import { closeDb, db, runMigrations } from "../src/shared/db/client.js";
import { creators, sessions, settlements, videos } from "../src/shared/db/schema.js";
import { env } from "../src/shared/env.js";
import { objectKeys, storage } from "../src/shared/storage.js";
import { parseExtinf } from "../src/shared/accounting.js";
import { chunkCount, cumulativeAmount, pricedChunkCount } from "../src/shared/price.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const DEMO_DIR = path.resolve(here, "../../frontend/public/demo");

const DEMO_VIDEOS = [
  { id: "v-consensus", asset: "d30", title: "Building a Hedera consensus node from scratch", description: "A walkthrough of the gossip, hashgraph and virtual-voting layers, with a live testnet demo at the end. Free preview for the first ten seconds.", price: "1000", free: 2, createdAt: "2026-09-04T10:00:00Z", seedViews: 402 },
  { id: "v-x402", asset: "d60", title: "x402 batch settlement explained in sixty seconds", description: "Why fifty sessions can close in one Hedera transaction, and what the voucher actually proves.", price: "1200", free: 0, createdAt: "2026-09-07T14:30:00Z", seedViews: 1180 },
  { id: "v-hts", asset: "d120", title: "HTS allowances vs. ERC-20 approvals", description: "Two minutes on how the Hedera Token Service exposes allowances to the EVM, and where the facade differs.", price: "2400", free: 1, createdAt: "2026-09-09T09:15:00Z", seedViews: 96 },
  { id: "v-mirror", asset: "d300", title: "Reading the Mirror Node like a pro", description: "Five minutes of REST endpoints, contract call simulation and the lag you have to design around.", price: "6000", free: 0, createdAt: "2026-09-10T18:45:00Z", seedViews: 27 },
];

async function main() {
  await runMigrations();
  const creatorId = "creator-seed";
  await db
    .insert(creators)
    .values({
      id: creatorId,
      wallet_address: env.SEED_CREATOR_WALLET.toLowerCase(),
      hedera_account_id: env.SEED_CREATOR_ACCOUNT_ID,
      handle: "ledgerlab",
      display_name: "Ledger Lab",
      world_nullifier_hash: "0xseed",
      verified_at: new Date("2026-09-01T00:00:00Z"),
      subscribers: 1284,
    })
    .onConflictDoNothing();

  for (const v of DEMO_VIDEOS) {
    const dir = path.join(DEMO_DIR, v.asset);
    if (!(await stat(dir).catch(() => undefined))) {
      console.warn(`skip ${v.id}: ${dir} missing (run 'pnpm demo:assets' in frontend/)`);
      continue;
    }
    const playlist = await readFile(path.join(dir, "index.m3u8"), "utf8");
    const durations = parseExtinf(playlist);
    const files = (await readdir(dir)).filter(f => /^seg-\d{4}\.ts$/.test(f)).sort();
    for (const [i, f] of files.entries()) {
      await storage.putStream(objectKeys.segment(v.id, i), createReadStream(path.join(dir, f)), "video/mp2t");
    }
    let thumbnailKey: string | null = null;
    if (await stat(path.join(dir, "thumb.jpg")).catch(() => undefined)) {
      await storage.putStream(objectKeys.thumbnail(v.id), createReadStream(path.join(dir, "thumb.jpg")), "image/jpeg");
      thumbnailKey = objectKeys.thumbnail(v.id);
    }
    const duration = durations.reduce((a, b) => a + b, 0);
    await db
      .insert(videos)
      .values({
        id: v.id,
        creator_id: creatorId,
        title: v.title,
        description: v.description,
        duration_seconds: duration,
        segment_count: durations.length,
        chunk_count: chunkCount(duration),
        segment_durations: durations,
        status: "ready",
        free_preview_chunks: v.free,
        total_price: v.price,
        thumbnail_key: thumbnailKey,
        seed_views: v.seedViews,
        created_at: new Date(v.createdAt),
        published_at: new Date(v.createdAt),
      })
      .onConflictDoUpdate({ set: { segment_durations: durations, segment_count: durations.length, chunk_count: chunkCount(duration), duration_seconds: duration, thumbnail_key: thumbnailKey, status: "ready" }, target: videos.id });
    console.log(`${v.id}: ${files.length} segments`);
  }

  // Historical settled sessions (three per video) so the session list and earnings are not empty.
  const settlementId = "seed-batch";
  await db
    .insert(settlements)
    .values({ id: settlementId, creator_id: creatorId, tx_hash: "0.0.10463136@1757500000.000000001", session_count: 0, submitted_at: new Date("2026-09-10T12:00:00Z"), confirmed_at: new Date("2026-09-10T12:00:04Z") })
    .onConflictDoNothing();
  const viewers = ["0x1a2b3c4d5e6f7081920a1b2c3d4e5f60718293a4", "0x9f8e7d6c5b4a39281706f5e4d3c2b1a0918273f6", "0x4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c4c"];
  let n = 0;
  for (const v of DEMO_VIDEOS) {
    const video = await db.query.videos.findFirst({ where: eq(videos.id, v.id) });
    if (!video) continue;
    const priced = pricedChunkCount(video.duration_seconds, video.free_preview_chunks);
    for (const [i, fraction] of [1, 0.6, 0.25].entries()) {
      n += 1;
      const consumed = Math.max(1, Math.round(priced * fraction));
      const amount = cumulativeAmount(BigInt(video.total_price), consumed, priced);
      const started = new Date(Date.parse(v.createdAt) + (i + 1) * 3_600_000);
      await db
        .insert(sessions)
        .values({
          id: `seed-${n}`,
          video_id: v.id,
          viewer_address: viewers[i % viewers.length],
          locked_amount: video.total_price,
          priced_chunk_count: priced,
          free_preview_chunks: video.free_preview_chunks,
          lock_tx: `0.0.10463136@${Math.floor(started.getTime() / 1000)}.${100 + n}`,
          started_at: started,
          ended_at: new Date(started.getTime() + consumed * 5000),
          last_activity_at: started,
          chunks_served: consumed + video.free_preview_chunks,
          chunks_consumed: consumed,
          paid_chunks: Array.from({ length: consumed }, (_, k) => video.free_preview_chunks + k),
          consumed_amount: amount.toString(),
          refunded_amount: (BigInt(video.total_price) - amount).toString(),
          refund_tx: `0.0.10463136@${Math.floor(started.getTime() / 1000) + 400}.${200 + n}`,
          status: "settled",
          settlement_id: settlementId,
        })
        .onConflictDoNothing();
    }
  }
  console.log("seed complete");
  await closeDb();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
